/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* **************************************************
 *			    	INCLUDES					    *
 *************************************************  */

#include <stm32f072x8.h>
#include <cortex_m0_config.h>
#include <stm32f0xx_gpio_driver.h>
#include <sys_adc.h>
#include <sys_frequency.h>
#include <sys_timer.h>
#include <NEC_transmission.h>

/* **************************************************
 *					DEFINES 					    *
 *************************************************  */

#define V_REF 3.3   /* Reference voltage */

#define R1 10000.0  /* Resistance at temperature T1 (in ohms) */
#define T1 25.0     /* Temperature at R1 (in Celsius) */

#define R2 12500.0  /* Resistance at temperature T2 (in ohms) */
#define T2 30.0     /* Temperature at R2 (in Celsius) */

/* **************************************************
 *			    GLOBAL VARIABLES 					*
 *************************************************  */

volatile float  f_temperature = 0.0f;
volatile float  f_resistance  = 0.0f;
volatile float  f_voltage     = 0.0f;
volatile uint32 u_adcValue    = 0u;

/* **************************************************
 *			    FUNCTION PROTOTYPE 					*
 *************************************************  */
extern void initialise_monitor_handles(void);
static void GPIO_Config(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/****************************************************/

static void GPIO_Config(void)
{
	GPIO_v_PeripheralClockControl(GPIOB, ENABLE);
	GPIO_v_PeripheralClockControl(GPIOA, ENABLE);

	GPIO_PinConfig_t GPIO_PinConfigurationPortB;
	GPIO_PinConfig_t GPIO_PinConfigurationPortA;

	/* Pin used as an input for IR receiver */
	GPIO_PinConfigurationPortB.GPIO_PinNumber = 12u;
	GPIO_PinConfigurationPortB.GPIO_PinMode = FALING_TRIGGER;
	GPIO_PinConfigurationPortB.GPIO_PinPuPdControl = PULL_UP;

	GPIO_v_Init(GPIOB, GPIO_PinConfigurationPortB);

	/* Interrupt configuration */
	GPIO_v_IRQInteruptConfig(IRQ_EXTI4_15, ENABLE);
	GPIO_v_IRQPrioConfig(IRQ_EXTI4_15, 1u);

	/* Analog pin configuration */
	GPIO_PinConfigurationPortB.GPIO_PinNumber = 1u;
	GPIO_PinConfigurationPortB.GPIO_PinMode = ANALOG_MODE;

	GPIO_v_Init(GPIOB, GPIO_PinConfigurationPortB);

	/* IR transmitter configuration. AF2 == TIM2_CH1_ETR */
	GPIO_PinConfigurationPortA.GPIO_PinNumber = 0u;
	GPIO_PinConfigurationPortA.GPIO_PinOPType = 0u;
	GPIO_PinConfigurationPortA.GPIO_PinMode = ALTERNATE_FUNCTION_MODE;
	GPIO_PinConfigurationPortA.GPIO_PinAltFunMode = AF2;

	GPIO_v_Init(GPIOA, GPIO_PinConfigurationPortA);

}

int main(void)
{
	initialise_monitor_handles();

	/* 16 MHz frequency */
	PLL_Enable(RCC_CFGR_PLLMUL4);

	/* Timer initialization */
	TIM3_v_cfg(16u);

	GPIO_Config();

	ADCx_u_Init(ADC1, 0u);

	TIM2_v_IrFrequencyCfg();

	while(1)
	{
		uint32 code = 0x807F02FDu;

		Delay_v_ms(15000u);

        NEC_v_SendMessage(&code, 1u);

        Delay_v_ms(1500u);

	    /*	Temperature measurement
	     *
	     * u_adcValue = ADCx_u_Read(ADC1);

	    f_voltage = (u_adcValue / 4095.0) * V_REF;

	    f_resistance = (V_REF * 10000.0 / f_voltage) - 10000.0;

	    float m = (T2 - T1) / (R2 - R1);
	    float b = T1 - m * R1;

	    f_temperature = m * f_resistance + b; */
	}
}
